<script setup lang="ts">
// Shared by the v2.1 and v2.2-rc1 payment API guides. The example URLs and
// the reference link below follow the version of the page being viewed:
// `protocolVersion` is the version inside the standard's own paths (v2.2),
// `docsVersion` is the route segment (v2.2-rc1).
const { docsVersion, protocolVersion } = useRouteVersion()

const examplePayload = computed(() => `{
  "message": {
    "Data": {
      "PaymentId": "83b47199-90c2-4c05-9ef1-aeae68b0fc7c",
      "ConsentId": "b8f42378-10ac-46a1-8d20-4e020484216d",
      "Status": "Pending",
      "StatusUpdateDateTime": "2026-05-03T15:46:01+00:00",
      "CreationDateTime": "2026-05-03T15:46:01+00:00",
      "Instruction": {
        "Amount": {
          "Amount": "100.00",
          "Currency": "AED"
        }
      },
      "PaymentPurposeCode": "ACM",
      "DebtorReference": "Invoice 1234",
      "OpenFinanceBilling": {
        "Type": "PushP2P"
      }
    },
    "Links": {
      "Self": "https://api.lfi.example/open-finance/payment/${protocolVersion.value}/payments/83b47199-90c2-4c05-9ef1-aeae68b0fc7c",
      "Related": "https://api.lfi.example/open-finance/${protocolVersion.value}/payment-consents/b8f42378-10ac-46a1-8d20-4e020484216d"
    }
  }
}
`)
</script>

<template>
  <div class="ag-step">
    <EdProse>
      A <code>201 Created</code> response is returned as a signed JWT (<code>application/jwt</code>).
      Verify the signature using the LFI's public signing key before reading the payload.
    </EdProse>

    <h4 class="ag-step__subhead ag-step__subhead--small">Response headers</h4>
    <EdRefTable>
      <table>
        <thead>
          <tr><th>Header</th><th>Description</th></tr>
        </thead>
        <tbody>
          <tr><td><code>Location</code></td><td>URL of the created payment resource &mdash; <code>/open-finance/payment/{{ protocolVersion }}/payments/{PaymentId}</code></td></tr>
          <tr><td><code>x-fapi-interaction-id</code></td><td>Echo of the interaction ID from the request</td></tr>
          <tr><td><code>x-idempotency-key</code></td><td>Echo of the idempotency key from the request</td></tr>
        </tbody>
      </table>
    </EdRefTable>

    <h4 class="ag-step__subhead ag-step__subhead--small">Response body — <code>Data</code></h4>
    <EdRefTable>
      <table>
        <thead>
          <tr><th>Field</th><th>Required</th><th>Description</th></tr>
        </thead>
        <tbody>
          <tr><td><code>PaymentId</code></td><td>Yes</td><td>LFI-assigned unique identifier for this payment resource (use this to poll for status)</td></tr>
          <tr><td><code>ConsentId</code></td><td>Yes</td><td>The consent this payment is bound to</td></tr>
          <tr><td><code>Status</code></td><td>Yes</td><td>Current payment status &mdash; see status lifecycle below</td></tr>
          <tr><td><code>StatusUpdateDateTime</code></td><td>Yes</td><td>ISO 8601 datetime of the last status change</td></tr>
          <tr><td><code>CreationDateTime</code></td><td>Yes</td><td>ISO 8601 datetime when the payment resource was created</td></tr>
          <tr><td><code>Instruction.Amount</code></td><td>Yes</td><td>Echoes back the amount and currency from the request</td></tr>
          <tr><td><code>PaymentPurposeCode</code></td><td>Yes</td><td>Echoes back the payment purpose code</td></tr>
          <tr><td><code>OpenFinanceBilling</code></td><td>Yes</td><td>Echoes back the billing parameters</td></tr>
          <tr><td><code>PaymentTransactionId</code></td><td>No</td><td>End-to-end transaction ID generated by the Aani payment rails once the payment is submitted for settlement. Not present at <code>Pending</code>.</td></tr>
          <tr><td><code>DebtorReference</code></td><td>No</td><td>Echoes back the debtor reference if provided</td></tr>
          <tr><td><code>RejectReasonCode</code></td><td>No</td><td>Array of <code>{ Code, Message }</code> objects &mdash; present only when <code>Status</code> is <code>Rejected</code></td></tr>
        </tbody>
      </table>
    </EdRefTable>

    <h4 class="ag-step__subhead ag-step__subhead--small">Status lifecycle</h4>
    <EdRefTable>
      <table>
        <thead>
          <tr><th>Status</th><th>Description</th></tr>
        </thead>
        <tbody>
          <tr><td><code>Pending</code></td><td>The payment has been accepted by the LFI and queued for processing. This is the typical status immediately after creation.</td></tr>
          <tr><td><code>AcceptedSettlementCompleted</code></td><td>The debtor's account has been debited.</td></tr>
          <tr><td><code>AcceptedWithoutPosting</code></td><td>The receiving LFI has accepted the payment but has not yet credited the creditor account.</td></tr>
          <tr><td><code>AcceptedCreditSettlementCompleted</code></td><td>The creditor account has been credited. Payment is fully settled.</td></tr>
          <tr><td><code>Rejected</code></td><td>The payment was rejected. Inspect <code>RejectReasonCode</code> for the reason.</td></tr>
        </tbody>
      </table>
    </EdRefTable>

    <h4 class="ag-step__subhead ag-step__subhead--small"><code>Links</code></h4>
    <EdRefTable>
      <table>
        <thead>
          <tr><th>Field</th><th>Description</th></tr>
        </thead>
        <tbody>
          <tr><td><code>Self</code></td><td>URL to this payment resource &mdash; use for status polling</td></tr>
          <tr><td><code>Related</code></td><td>URL to the associated consent &mdash; <code>/open-finance/{{ protocolVersion }}/payment-consents/{ConsentId}</code></td></tr>
        </tbody>
      </table>
    </EdRefTable>

    <h4 class="ag-step__subhead ag-step__subhead--small">Example response payload</h4>
    <EdProse>
      The payload is the verified body of the signed JWT. Per <code>AEPaymentIdResponseSigned</code>,
      <code>Data</code> and <code>Links</code> are wrapped in a <code>message</code> envelope.
    </EdProse>

    <EdCode :code="examplePayload" lang="json" filename="201 Created — decoded JWT body" />

    <EdNote type="tip" title="Store the PaymentId">
      <p>
        Persist <code>PaymentId</code> immediately &mdash; it is required to poll
        <code>GET /payments/{PaymentId}</code> for status updates. A payment typically moves from
        <code>Pending</code> to a terminal status within seconds, but network conditions may require
        polling.
      </p>
    </EdNote>

    <EdProse>
      See the
      <a :href="`/tech/tpp-standards/${docsVersion}/banking/service-initiation/open-api/payments`">POST /payments</a>
      API reference for the full request and response schema.
    </EdProse>
  </div>
</template>

<style scoped>
.ag-step__subhead {
  font-family: var(--at-serif);
  font-size: 1.25rem;
  font-weight: 600;
  letter-spacing: -0.015em;
  color: var(--at-navy-deep);
  margin: 1.75rem 0 0.85rem;
}
.ag-step__subhead--small { font-size: 1.05rem; }
.ag-step__subhead :deep(code) {
  font-family: var(--at-mono);
  font-size: 0.8em;
  background: color-mix(in srgb, var(--at-grid-line) 55%, var(--at-bg-cream));
  border: 1px solid var(--at-grid-line);
  padding: 0.08em 0.4em;
}
</style>
