<route lang="yaml">
meta:
  title: Trust Framework — Sign Up
</route>

<template>
  <div class="ed-doc">
    <section class="ed-doc__hero">
      <div class="ed-doc__inner">
        <div class="ed-doc__eyebrow">
          <span class="ed-doc__eyebrow-dash" />
          TPP · Trust Framework · Onboarding
        </div>
        <h1 class="ed-doc__title">
          Sign Up
          <span class="ed-doc__read">2 min read</span>
        </h1>
        <p class="ed-doc__lede">
          This guide walks through the steps a newly invited Organisation Admin or User must complete
          after receiving an invitation to the Trust Framework platform.
        </p>
      </div>
    </section>

    <EdSectionBand
      id="sign-up-steps"
      num="01"
      color="var(--at-teal)"
      eyebrow="Sign Up"
      title="9 steps from invitation email to platform access"
      tone="cream"
    >
      <ol class="ed-doc__steps">
        <li>
          <h3>Receive Onboarding Email</h3>
          <EdProse>
            Once you have been invited, you will receive an email from the
            <strong>Al Tareq Trust Framework Sandbox</strong>. This email contains a registration link
            &mdash; keep it to hand before proceeding.
          </EdProse>
          <ImageViewer src="/images/raidiam/sign-up/1.png" alt="Onboarding email containing the registration link" />
        </li>

        <li>
          <h3>Open the Registration Link</h3>
          <EdProse>Click on the registration link provided in the email.</EdProse>
        </li>

        <li>
          <h3>Access the Sign-In Page</h3>
          <EdProse>
            You will be redirected to the Trust Framework Sandbox sign-in page. Click
            <strong>Registration</strong> to begin the registration process.
          </EdProse>
          <ImageViewer src="/images/raidiam/sign-up/2.png" alt="Trust Framework Sign-In Page — click Registration" />
        </li>

        <li>
          <h3>Complete Registration</h3>
          <EdProse>Fill in the required registration details and submit your request.</EdProse>
          <EdNote type="warning">
            <p>
              Make sure the email address you register with exactly matches the email address you were
              invited with.
            </p>
          </EdNote>
          <ImageViewer src="/images/raidiam/sign-up/3.png" alt="Complete Registration — use your invited email address" />
        </li>

        <li>
          <h3>Set Up Two-Factor Authentication</h3>
          <EdProse>
            Scan the QR code displayed on screen using <strong>Google Authenticator</strong> or another
            authenticator app of your choice. Enter the one-time code generated by the app to complete the
            setup.
          </EdProse>
          <ImageViewer src="/images/raidiam/sign-up/4.png" alt="Set up Multi-Factor by scanning the QR code with your authenticator app" />
        </li>

        <li>
          <h3>Accept Terms of Acceptance</h3>
          <EdProse>
            After successful registration, you will receive another email at your registered email address
            requesting you to review and accept the <strong>Terms of Acceptance</strong> from the Al Tareq
            Platform.
          </EdProse>
          <ImageViewer src="/images/raidiam/sign-up/5.png" alt="Terms of Acceptance email" />
        </li>

        <li>
          <h3>Review and Sign the Document</h3>
          <EdProse>Open the Terms of Acceptance document and electronically sign it.</EdProse>
          <ImageViewer src="/images/raidiam/sign-up/6.png" alt="Review and sign the Terms of Acceptance" />
        </li>

        <li>
          <h3>Check Your Request Status</h3>
          <EdProse>
            Return to the
            <a href="https://web.sandbox.directory.openfinance.ae/">Trust Framework Sandbox portal</a> and
            check the status of your registration request.
          </EdProse>
          <ImageViewer src="/images/raidiam/sign-up/7.png" alt="Check status in the Sandbox Portal after signing" />
        </li>

        <li>
          <h3>Log In to the Platform</h3>
          <EdProse>
            Once the process is completed, you will be able to log in to the Trust Framework Sandbox and
            access the resources your role permits.
          </EdProse>
        </li>
      </ol>
    </EdSectionBand>
  </div>
</template>

<style scoped>
.ed-doc {
  background: var(--at-bg-cream);
  color: var(--at-navy-deep);
  font-family: var(--at-sans);
  padding-top: 4.25rem;
  min-height: 100vh;
}

.ed-doc__hero { background: var(--at-bg-cream); border-bottom: 1px solid var(--at-grid-line); }
.ed-doc__inner { max-width: var(--at-page-max); margin: 0 auto; padding: 4rem 2rem 3rem; }

.ed-doc__eyebrow {
  font-family: var(--at-mono);
  font-size: 0.68rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: var(--at-teal);
  margin-bottom: 1.25rem;
  display: flex;
  align-items: center;
  gap: 0.75rem;
}
.ed-doc__eyebrow-dash { width: 24px; height: 1px; background: currentColor; }

.ed-doc__title {
  font-family: var(--at-serif);
  font-size: clamp(2.25rem, 5vw, 3.6rem);
  font-weight: 600;
  line-height: 1.02;
  letter-spacing: -0.03em;
  margin: 0;
  display: flex;
  align-items: baseline;
  flex-wrap: wrap;
  gap: 0.85rem;
}
.ed-doc__read {
  font-family: var(--at-mono);
  font-size: 0.7rem;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  font-weight: 500;
  color: var(--at-mute);
  align-self: center;
  padding-left: 0.6rem;
  border-left: 1px solid var(--at-grid-line-2);
}

.ed-doc__lede {
  font-family: var(--at-sans);
  font-size: 1.1rem;
  line-height: 1.65;
  margin: 1.75rem 0 0;
  max-width: 50rem;
  color: var(--at-mute-2);
}

.ed-doc__steps {
  list-style: none;
  counter-reset: ed-step;
  padding: 0;
  margin: 0;
  display: flex;
  flex-direction: column;
  gap: 2rem;
}
.ed-doc__steps > li {
  counter-increment: ed-step;
  position: relative;
  padding-left: 3.5rem;
  min-height: 2.5rem;
}
.ed-doc__steps > li::before {
  content: counter(ed-step, decimal-leading-zero);
  position: absolute;
  left: 0;
  top: 0;
  width: 2.5rem;
  height: 2.5rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: var(--at-navy-deep);
  color: var(--at-bg-cream);
  font-family: var(--at-mono);
  font-size: 0.85rem;
  font-weight: 700;
  letter-spacing: 0.04em;
}
.ed-doc__steps > li > h3 {
  font-family: var(--at-serif);
  font-size: 1.2rem;
  font-weight: 600;
  letter-spacing: -0.015em;
  color: var(--at-navy-deep);
  margin: 0.25rem 0 0.85rem;
}

@media (max-width: 720px) {
  .ed-doc__inner { padding: 2.75rem 1.25rem 2rem; }
  .ed-doc__steps > li { padding-left: 2.75rem; }
  .ed-doc__steps > li::before { width: 2rem; height: 2rem; font-size: 0.75rem; }
}
</style>
