export const purposeCodes = {
  "ACM": "Agency Commission",
  "CCP": "Customer Card Payment",
  "CHC": "Charitable Contributions",
  "CRP": "Credit Card Payment",
  "POS": "Merchant Settlements",
  "AES": "Advance Payment against",
  "ALW": "Allowance",
  "BON": "Bonus",
  "CIN": "Commercial Investments",
  "COM": "Commission",
  "COP": "Compensation",
  "DCP": "Debit Card Payment", // Also used for Pre-Paid Reloadable & Personalized Debit Card Payments
  "DIV": "Dividend Payouts",
  "EDU": "Educational Support",
  "EMI": "Equated Monthly Installments",
  "EOS": "End of service final settlement",
  "IPO": "IPO Subscriptions",
  "LAS": "Leave Salary",
  "LIP": "Loan Interest Payments",
  "LNC": "Loan Charges",
  "LND": "Loan Disbursements",
  "MCR": "Medical Claim Reimbursements",
  "OVT": "Over Time",
  "PEN": "Pension",
  "POR": "Refunds/Reversals on IPO",
  "RNT": "Rent Payments",
  "SAA": "Salary Advance",
  "SAL": "Salary",
  "TKT": "Tickets",
  "UTL": "Utility", // Listed as ULT, but likely UTL for Utility Bill Payments
  "TOF": "Transfer of funds between persons Normal and Juridical", // This could correspond to P2P (Peer-to-Peer) transfers
  "IGT": "Inter Group Transfer",
  "OAT": "Own Account Transfer",
  "SVI": "Stored Value Card Cash - In",
  "SVO": "Stored Value Card Cash - Out",
  "SVP": "Stored Value Card Payments",
  "MWI": "Mobile Wallet Cash In",
  "MWO": "Mobile Wallet Cash Out",
  "MWP": "Mobile Wallet Payments",
  "PRP": "Profit rate Swap Payments",
  "PRW": "Profit Rate Unwind Payments",
  "IRP": "Interest Rate Swap Payments",
  "IRW": "Interest Rate Unwind Payments",
  "GDS": "Goods Bought or Sold",
  "GMS": "Processing repair and maintenance services on goods",
  "STS": "Sea transport",
  "ATS": "Air transport",
  "OTS": "Other modes of transport",
  "STR": "Travel",
  "SCO": "Construction",
  "INS": "Insurance services",
  "FIS": "Financial services",
  "IPC": "Charges for the use of intellectual property royalties",
  "TCS": "Telecommunication services",
  "ITS": "Computer services",
  "IFS": "Information services",
  "RDS": "Research and development services",
  "PMS": "Professional and management consulting services",
  "TTS": "Technical trade-related and other business services",
  "PRS": "Personal cultural audio visual and recreational services",
  "GOS": "Government goods and services embassies etc",
  "IGD": "Intra group dividends",
  "IID": "Intra group interest on debt",
  "PIP": "Profits on Islamic products",
  "PRR": "Profits or rents on real estate",
  "DOE": "Dividends on equity not intra group",
  "ISH": "Income on investment funds shares",
  "ISL": "Interest on securities more than a year",
  "ISS": "Interest on securities less than a year",
  "IOL": "Income on loans",
  "IOD": "Income on deposits",
  "GRI": "Government related income taxes tariffs capital transfers etc",
  "CEA": "Equity for the establishment of new company from residents abroad equity of merger or acquisition of companies abroad from residents and participation to capital increase of related company abroad",
  "PPA": "Purchase of real estate abroad from residents",
  "DLF": "Debt instruments intragroup loans securities deposits foreign", // Listed as DIF, but likely DLF
  "FSA": "Equity other than investment fund shares in t related companies abroad",
  "FIA": "Investment fund shares foreign",
  "DSA": "Purchases and sales of foreign debt securities less than a year in t related companies",
  "DLA": "Purchases and sales of foreign debt securities more than a year in t related companies",
  "FDA": "Financial derivatives foreign",
  "AFA": "Receipts or payments from personal residents bank account or deposits abroad",
  "SLA": "Loans - Drawings or Repayments on loans extended to n-residents - short term",
  "LLA": "Loans - Drawings or Repayments on loans extended to n-residents - long term",
  "LEA": "Leasing abroad",
  "RFS": "Repos on foreign securities",
  "TCR": "Trade credits and advances receivable",
  "CEL": "Equity for the establishment of new company in the UAE from residents equity of merger or acquisition of companies in the UAE from n-residents participation to capital increase of related companies",
  "PPL": "Purchase of real estate in the UAE from n- residents",
  "LDL": "Debt instruments intragroup loans securities deposits in the UAE", // Listed as DIL, but likely LDL
  "FSL": "Equity other than investment fund shares in t related companies in the UAE",
  "FIL": "Investment fund shares in the UAE",
  "DSL": "Purchases and sales of securities issued by residents less than a year in t related companies",
  "DLL": "Purchases and sales of securities issued by residents more than a year in t related companies",
  "FDL": "Financial derivatives in the UAE",
  "AFL": "Receipts or payments from personal n- resident bank account in the UAE",
  "SLL": "Loans - Drawings or Repayments on foreign loans extended to residents - short term",
  "LLL": "Loans - Drawings or Repayments on foreign loans extended to residents - long term",
  "LEL": "Leasing in the UAE",
  "RLS": "Repos on securities issued by residents",
  "TCP": "Trade credits and advances payable"
} as const

export type PurposeCode = keyof typeof purposeCodes

export function getPurposeDescription(code?: string): string {
  if (!code) return "Unknown code"
  const upperCode = code.toUpperCase() as PurposeCode
  return purposeCodes[upperCode] ?? "Unknown code"
}